# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b38378216ded7822bd154c106a8ab03e14397f91df2b8ccdf56cbdff215e427d4fda16f9d58e41e7fdbf3f525dbf90493ecba1e36addbcce0d7d6fd097e8d33

test:
  secret_key_base: 17136e8856a40d320b19af1838e7bb67290a33af9cd95673035fb1ae3cf06f96c37992c01ecb23d72f22faaaca0726308cbf78accca8539d4286cf60ba3e979b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
